### ISSUE TITLE
are you working on this awesome pack?

### ISSUE THREAD

**Issue by cijagani** [yidas/codeigniter-pack#2]
nice to see this pack. it has amazing packages. I would like to know that are you still working on this project?

if yes then I have webpack scripts that will manage jquery, bootstrap, other CSS, and js libraries with many kinds of stuff like live sync, minify, marge js and css etc..

i would like to submit PR

**Comment by truelineinfotech** [comment]
I can submit PR

**Comment by yidas** [comment]
Hi @truelineinfotech,

Thanks for your appreciation.

Can you provide the library you describe? I would like to check it.

**Comment by cijagani** [comment]
nothing fancy. i am using [laravel mix](https://laravel-mix.com/).  it is an elegant wrapper of [Webpack](https://webpack.js.org/).

here is a [documentation](https://laravel-mix.com/docs/5.0/installation) of laravel mix.. we can use in any project. core php or any other framework.

**Comment by yidas** [comment]
Hi @truelineinfotech,

I would like to know how to integrate with CodeIgniter?

Thanks.

**Comment by cijagani** [comment]
sure @yidas .
i already integrated wtih latest ci.
here is link https://github.com/truelineinfotech/codeiginter-boilerplate.git
truelineinfotech/codeiginter-boilerplate
